# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "Notebook" -%}
  - fs
  - pathlib
  - ipykernel
  {% endif -%}
  - pip
  - pyprojroot
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages == "Script" -%}
    - pyhere
    {% endif -%}